#
# Travis CI configuration
#

language: python

python:
  - "3.5"
  - "nightly"

install:
  - pip install -qU pytest pytest-cov python-coveralls pytest-asyncio

script:
  - python setup.py pytest --addopts '--cov=growler --cov-report=term-missing'

after_success:
  - coveralls
